In [126]:
import pandas as pd

## Data Reading

In [127]:
df=pd.read_csv(r'C:\Users\saba\Downloads\data.csv')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Head() shows 1st 5 rows

In [128]:
# undefined number of rows e.g, when number is not given head() will print only first 5 rows
print(df.head())

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [129]:
# defiined number of rows e.g, 12
print(df.head(12))

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7

## Tail() shows last 5 rows

In [130]:
# tail() will print last 5 rows
print(df.tail())

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Check shape(rows and column)

In [131]:
print(df.shape)

(32, 5)

In [132]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

In [133]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [134]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [135]:
df["Pulse"].max()

np.int64(130)

In [136]:
df["Duration"].min()

np.int64(30)

In [137]:
df["Calories"].mean()

np.float64(304.68)

In [138]:
print(pd.options.display.max_rows)

60

## info()

In [139]:
# Gives you more information about data like(non-null values, columns, data type)
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB
None

## DATA CLEANING TASKS

In [140]:
# fillna() will replace null value instead removing entire cell
df.fillna({"Calories": 130}, inplace=True) # but you have to specify the column in which you want to make changes 
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [141]:
df.fillna({'Date':'Unknown'}, inplace=True) # this will make changes in specific column (Date column only)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45       Unknown    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Wrong format

In [146]:
# Row 22 and 26 have wrong date format 
# to_datetime() is used to fix this
df1=pd.read_csv(r'c:\Users\saba\Downloads\data.csv')
df1

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Date column into datetime format

In [147]:
# to_datetime() function fix wrong date to default pandas format
df1['Date'] = pd.to_datetime(df1['Date'], format='mixed')
df1

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

## Identifying missing values

In [148]:
print(df1.isnull().sum())

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

#  Replacing missing Calories values with the mean Calories

In [149]:
df_mean = df1["Calories"].mean()
df1["Calories"].fillna(df_mean)

0     409.10
1     479.00
2     340.00
3     282.40
4     406.00
5     300.00
6     374.00
7     253.30
8     195.10
9     269.00
10    329.30
11    250.70
12    250.70
13    345.30
14    379.30
15    275.00
16    215.20
17    300.00
18    304.68
19    323.00
20    243.00
21    364.20
22    282.00
23    300.00
24    246.00
25    334.50
26    250.00
27    241.00
28    304.68
29    280.00
30    380.30
31    243.00
Name: Calories, dtype: float64

## Finding and removing duplicate rows

In [185]:
# Finding duplicates
df1.duplicated().sum()

np.int64(1)

In [186]:
# Removing duplicates
df1.drop_duplicates()

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [152]:
# Another way to find and remove duplictaes
df1.drop_duplicates(inplace=True)
df1

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

# Detecting and fixing incorrect Durtaion (450) minutes

In [153]:
df1.Duration.replace(450,45)

0     60
1     60
2     60
3     45
4     45
5     60
6     60
7     45
8     30
9     60
10    60
11    60
13    60
14    60
15    60
16    60
17    60
18    45
19    60
20    45
21    60
22    45
23    60
24    45
25    60
26    60
27    60
28    60
29    60
30    60
31    60
Name: Duration, dtype: int64

# Remove rows where Date is missing

In [154]:
# NaT can be handled by removing entire row using bdropna()
df1.dropna(subset=['Date'], inplace = True)
df1

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

## Replace the date format "20201226" with proper datetime format

# Replace for specific columns

In [155]:
df1=pd.read_csv(r'c:\Users\saba\Downloads\data.csv')
df1
new_df = df["Calories"].fillna(130)
new_df

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18    130.0
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28    130.0
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

## Select rows where Duration is greater than 60 minutes

In [157]:
df1[df1["Duration"] > 60]

   Duration       Date  Pulse  Maxpulse  Calories
7       450 2020-12-08    104       134     253.3

## Select rows where Pulse > 110

In [158]:
df1[df1["Pulse"] > 110]

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
23        60 2020-12-23    130       101     300.0

# Filter rows where Calories burned are greater than 350

In [159]:
df1[df1["Calories"] > 350]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
6         60 2020-12-07    110       136     374.0
14        60 2020-12-14    104       132     379.3
21        60 2020-12-21    108       131     364.2
30        60 2020-12-30    102       129     380.3

## Select rows where Pulse is between 100 and 110

In [160]:
df1[(df1["Pulse"] >= 100) & (df1["Pulse"] <= 110)]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3

# Display only Duration and Calories columns

In [161]:
df1[["Duration","Calories"]]

    Duration  Calories
0         60     409.1
1         60     479.0
2         60     340.0
3         45     282.4
4         45     406.0
5         60     300.0
6         60     374.0
7        450     253.3
8         30     195.1
9         60     269.0
10        60     329.3
11        60     250.7
12        60     250.7
13        60     345.3
14        60     379.3
15        60     275.0
16        60     215.2
17        60     300.0
18        45       NaN
19        60     323.0
20        45     243.0
21        60     364.2
22        45     282.0
23        60     300.0
24        45     246.0
25        60     334.5
26        60     250.0
27        60     241.0
28        60       NaN
29        60     280.0
30        60     380.3
31        60     243.0

## Calculate the average Pulse for the dataset

In [162]:
df1["Pulse"].mean()

np.float64(103.5)

## Find the day with the highest Calories burned.

In [163]:
df1.loc[df1["Calories"].idxmax(), "Date"]

Timestamp('2020-12-02 00:00:00')

## Find the total Calories burned in December.

In [164]:
df1["Calories"].sum()

np.float64(9140.4)

## Calculate the average Duration of workouts.

In [ ]:
df1["Duration"].mean()

np.float64(68.4375)

##  Find the maximum Maxpulse value

In [166]:
df1["Maxpulse"].max()

np.int64(175)

## Sorting & Grouping Tasks

## Sort the dataset by Calories burned (descending).

In [167]:
df1.sort_values(by="Calories", ascending=False)

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3
6         60 2020-12-07    110       136     374.0
21        60 2020-12-21    108       131     364.2
13        60 2020-12-13    106       128     345.3
2         60 2020-12-03    103       135     340.0
25        60 2020-12-25    102       126     334.5
10        60 2020-12-11    103       147     329.3
19        60 2020-12-19    103       123     323.0
23        60 2020-12-23    130       101     300.0
5         60 2020-12-06    102       127     300.0
17        60 2020-12-17    100       120     300.0
3         45 2020-12-04    109       175     282.4
22        45        NaT    100       119     282.0
29        60 2020-12-29    100       132     280.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
7        450 2020-12-08    104       134     253.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
24        45 2020-12-24    105       132     246.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
27        60 2020-12-27     92       118     241.0
16        60 2020-12-16     98       120     215.2
8         30 2020-12-09    109       133     195.1
18        45 2020-12-18     90       112       NaN
28        60 2020-12-28    103       132       NaN

## 30. Sort the dataset by Pulse (ascending).

In [168]:
df1.sort_values(by="Pulse", ascending=True)

    Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112       NaN
27        60 2020-12-27     92       118     241.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
16        60 2020-12-16     98       120     215.2
11        60 2020-12-12    100       120     250.7
17        60 2020-12-17    100       120     300.0
22        45        NaT    100       119     282.0
29        60 2020-12-29    100       132     280.0
12        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
5         60 2020-12-06    102       127     300.0
30        60 2020-12-30    102       129     380.3
25        60 2020-12-25    102       126     334.5
28        60 2020-12-28    103       132       NaN
10        60 2020-12-11    103       147     329.3
2         60 2020-12-03    103       135     340.0
19        60 2020-12-19    103       123     323.0
7        450 2020-12-08    104       134     253.3
14        60 2020-12-14    104       132     379.3
24        45 2020-12-24    105       132     246.0
13        60 2020-12-13    106       128     345.3
21        60 2020-12-21    108       131     364.2
3         45 2020-12-04    109       175     282.4
8         30 2020-12-09    109       133     195.1
0         60 2020-12-01    110       130     409.1
6         60 2020-12-07    110       136     374.0
4         45 2020-12-05    117       148     406.0
1         60 2020-12-02    117       145     479.0
23        60 2020-12-23    130       101     300.0

## Group the data by Duration and calculate average Pulse

In [169]:
df1.groupby("Duration")["Pulse"].mean()

Duration
30     109.000
45     103.000
60     103.375
450    104.000
Name: Pulse, dtype: float64

##  Find the top 5 workouts with the highest Calories burned.

In [170]:
df1.nlargest(5, "Calories")

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

## Aggregation and Statistics

## Calculate average Pulse.

In [171]:
df1["Pulse"].mean()

np.float64(103.5)

## Calculate average Duration

In [172]:
df1["Duration"].mean()

np.float64(68.4375)

## Find maximum Calories burned.

In [173]:
df1["Calories"].max()

np.float64(479.0)

## Find minimum Pulse.

In [174]:
df1["Pulse"].min()

np.int64(90)

## Find total Calories burned.

In [175]:
df1["Calories"].sum()

np.float64(9140.4)



## Count how many workouts have Duration = 60.

In [176]:
df1[df1["Duration"] == 60].shape[0]

24

## Group by operations

## Group dataset by Duration and calculate average Calories.

In [177]:
df1.groupby("Duration")["Calories"].mean()

Duration
30     195.10000
45     291.88000
60     314.46087
450    253.30000
Name: Calories, dtype: float64




## Group by Duration and calculate average Pulse.

In [178]:
df1.groupby("Duration")["Pulse"].mean()

Duration
30     109.000
45     103.000
60     103.375
450    104.000
Name: Pulse, dtype: float64

## Find maximum Pulse for each Duration group.

In [179]:
df1.groupby("Duration")["Pulse"].max()

Duration
30     109
45     117
60     130
450    104
Name: Pulse, dtype: int64

## Count number of workouts per Duration category.

In [180]:
df1.groupby("Duration").size()

Duration
30      1
45      6
60     24
450     1
dtype: int64

## Mini Project Challenge

## Which day had the highest calorie burn?

In [181]:
df1.loc[df1["Calories"].idxmax(), "Date"]

Timestamp('2020-12-02 00:00:00')

## What is the average workout duration?

In [182]:
df1["Duration"].mean()

np.float64(68.4375)

## Which workout had the highest Pulse rate?

In [183]:
df1.loc[df1["Pulse"].idxmax()]

Duration                     60
Date        2020-12-23 00:00:00
Pulse                       130
Maxpulse                    101
Calories                  300.0
Name: 23, dtype: object

## What is the average Calories burned per minute?

In [184]:
(df1["Calories"] / df1["Duration"]).mean()

np.float64(5.3346888888888895)