In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [4]:
import matplotlib.pyplot as plt

In [11]:
df1=pd.read_csv(r"c:\Users\HP\Downloads\student_data_clean.csv")
df1

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,1026,Student_25,18,Other,Math,8,2.01,89.0,False,2022-05-23,3,17,Multan,9,Installment
1026,1027,Student_26,21,Other,BBA,6,3.87,57.0,False,2021-02-12,15,13,Karachi,8,Full
1027,1028,Student_27,19,Female,Math,1,3.64,89.0,False,2020-10-26,7,17,Islamabad,8,Installment
1028,1029,Student_28,23,Male,EE,5,3.62,93.0,True,2022-06-26,15,27,Islamabad,5,Pending
1029,1030,Student_29,22,Other,Math,2,3.77,72.0,False,2021-08-24,26,23,Islamabad,9,Full

In [12]:
df1.duplicated

<bound method DataFrame.duplicated of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [13]:
df1.isnull

<bound method DataFrame.isnull of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [14]:
df1.head(7)

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
5,1006,Student_5,22,Male,Math,1,3.86,78.0,False,2020-08-08,29,21,Lahore,2,NaN
6,1007,Student_6,22,Female,Math,3,2.06,68.0,False,2022-05-02,8,23,Islamabad,2,Full

In [15]:
df1.tail

<bound method NDFrame.tail of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [16]:
df1.drop

<bound method DataFrame.drop of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [17]:
df1.dropna

<bound method DataFrame.dropna of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [18]:
df1.drop_duplicates

<bound method DataFrame.drop_duplicates of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [19]:
df1.shape

(1030, 15)

In [20]:
df1.dtypes

Student_ID               int64
Name                       str
Age                      int64
Gender                     str
Department                 str
Semester                 int64
CGPA                   float64
Attendance_Rate        float64
Scholarship               bool
Admission_Date             str
Midterm_Marks            int64
Final_Marks              int64
City                       str
Study_Hours_Per_Day      int64
Fees_Paid                  str
dtype: object

In [22]:
import seaborn as sn

In [23]:
df1.info

<bound method DataFrame.info of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [24]:
df1.describe

<bound method NDFrame.describe of       Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]>

In [26]:
df1.isnull().sum()

Student_ID              0
Name                    0
Age                     0
Gender                  0
Department              0
Semester                0
CGPA                   51
Attendance_Rate        31
Scholarship             0
Admission_Date          0
Midterm_Marks           0
Final_Marks             0
City                    0
Study_Hours_Per_Day     0
Fees_Paid              22
dtype: int64

In [35]:
pivot=pd.pivot_table(df1,values="CGPA",
                     index="Gender",
                     aggfunc="mean")
pivot

            CGPA
Gender
Female  3.022389
Male    3.081929
Other   3.033354

In [38]:
pivot=pd.pivot_table(df1,values="Attendance_Rate",index="Gender",aggfunc="count")
pivot

        Attendance_Rate
Gender
Female              329
Male                332
Other               338

In [39]:
pivot=pd.pivot_table(df1,values='Attendance_Rate',index='Student_ID',columns='Gender',aggfunc="mean")
pivot

Gender      Female  Male  Other
Student_ID
1001           NaN   NaN   61.0
1002          98.0   NaN    NaN
1003           NaN   NaN   66.0
1004           NaN  91.0    NaN
1005           NaN  79.0    NaN
...            ...   ...    ...
1996           NaN  81.0    NaN
1997           NaN   NaN   89.0
1998          62.0   NaN    NaN
1999           NaN   NaN   69.0
2000          84.0   NaN    NaN

[970 rows x 3 columns]